name: task_wise_frontend
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  dotted_border: ^2.0.0+1
  http: ^0.13.3
  timeline_tile: ^2.0.0
  google_fonts: ^4.0.4
  dio: ^4.0.0
  random_color: ^1.0.5
  get_it: ^7.0.3
  intl: ^0.17.0
  table_calendar: ^3.0.8
  mask_text_input_formatter: ^2.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  provider: ^6.1.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/imagemTeste.jpg
